### ISSUE TITLE
Helm install suggestion not correct

### ISSUE THREAD

**Issue by Truxnell** [whazor/k8s-at-home-search#10]
*Tested on commit: https://github.com/whazor/k8s-at-home-search/commit/1b139fb5472241311f165669aff9beac1a3e3557*

In the helm install part of the new search, the helm install is not correct and is not workig well with app-template (or possibly all helms).

For example, when searching for a 'chart' i use (`invidious-server`) the helm install suggestion is to install `invidious-server` from bjw-s charts, when im actually using bjw-s `app-template`.  Might 'just' be using the wrong var to build the string?
```
Install
Install with:

helm repo add bjw-s-charts https://bjw-s.github.io/helm-charts/
helm install invidious-server bjw-s-charts/invidious-server -f values.yaml
```

**Comment by whazor** [comment]
Now resolved, I accidentally used the name instead of the chart name. This happened after refactoring when I went from chart name to release name.
