### ISSUE TITLE
variables in the HelmRelease name seem to throw it off

### ISSUE THREAD

**Issue by tyzbit** [whazor/k8s-at-home-search#17]
See https://nanne.dev/k8s-at-home-search/#grav

None of the links work, ex: https://nanne.dev/k8s-at-home-search/hr/tyzbit.github.io-helm-charts-grav-grav-techblogname

**Comment by whazor** [comment]
All the dynamic links are currently broken. There are dynamic and static pages. I only generate the static pages for releases with more than 3 deployments.

**Comment by whazor** [comment]
Closing in favor of #13
