### ISSUE TITLE
Change color for button to change search mode

### ISSUE THREAD

**Issue by Bykow** [whazor/k8s-at-home-search#22]
Just discovered that this square is actually a button.

On the dark theme, it does not display nicely, so it's hard to guess....

A simple color change would make a big difference, I've been using the tool for months, just discovered this grep feature !

![image](https://github.com/whazor/k8s-at-home-search/assets/23238577/8e7ce59d-2214-4424-814b-530620461546)

**Comment by whazor** [comment]
Hi, I think this is done.
