### ISSUE TITLE
Indexes old github usernames

### ISSUE THREAD

**Issue by binaryn3xus** [whazor/k8s-at-home-search#26]
It seems like if a github user is indexed once and then later change their github username, both start showing in searches.

So for example, I changed my github username about a year ago. However, my old username still shows up in the search and is accurate to changes from a day or so ago. (Minus stars)

Example: [https://kubesearch.dev/hr/ghcr.io-bjw-s-helm-app-template-lavalink#hr%20](https://kubesearch.dev/hr/ghcr.io-bjw-s-helm-app-template-lavalink#hr%20)

![image](https://github.com/user-attachments/assets/e4bace06-69d1-4623-aaba-62751b921c82)

Context: I changed my username from joshuagarrison27 to binaryn3xus

**Comment by whazor** [comment]
yeah, because the github API is so unreliable. Kubesearch uses a cached [repos.json](https://github.com/whazor/k8s-at-home-search/blob/main/repos.json).

**Comment by whazor** [comment]
That would indeed work.

**Comment by binaryn3xus** [comment]
#27 was created :)

**Comment by whazor** [comment]
:+1: it will be live tomorrow.

**Comment by binaryn3xus** [comment]
Thank you kindly for your support!
