### ISSUE TITLE
Webpage doesn't work on Safari (Possibly due to Regex?)

### ISSUE THREAD

**Issue by ck3mp** [Whazor/k8s-at-home-search#6]
When loading the page on Safari the user is presented with a blank page. 

This is present in the network log for the page:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/37331850/169047463-8f6e6ea7-7362-4073-9a09-40c685d9fdd1.png">

```
SyntaxError: Invalid regular expression: invalid group specifier name
N promiseReactionJob
```

A quick search suggests its a look-behind regex issue:

https://stackoverflow.com/questions/68525971/angular-doesnt-work-for-safari-browser-promisereactionjob-error

I am no web-dev so not comfortable to build a PR.

**Comment by Whazor** [comment]
Resolved
